name: R Tests
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Testing-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Cache R package library
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ~/.R
        key: ${{ runner.os }}-R-${{ hashFiles('renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-R-

    # Cache renv dependencies
    - name: Cache renv cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set up R library environment
      uses: r-lib/actions/setup-r@v2

    # Install renv before restoring
    - name: Install renv
      run: |
        Rscript -e "install.packages('renv', repos = 'https://cran.rstudio.com/')"

    # Restore renv environment using lockfile
    - name: Restore renv environment
      run: |
        Rscript -e "renv::restore()"

    - name: Run Tests
      run: |
        Rscript -e "devtools::load_all(); testthat::test_dir('tests/testthat')"